---
- name: "create temp dir"
  tempfile:
    state: directory
  register: tempdir

- name: "mount {{ target_device }} to {{ tempdir.path }}"
  mount:
    path: "{{ tempdir.path }}"
    src: "{{ target_device }}"
    fstype: ext4
    state: mounted

- name: "sync {{ directory_to_move }} to {{ tempdir.path }}"
  synchronize:
    src: "{{ directory_to_move }}"
    dest: "{{ tempdir.path }}"
    perms: yes
    delegate_to: {{ inventory_host }}

- name: "unmount {{ target_device }} from {{ tempdir.path }}"
  mount:
    path: "{{ tempdir.path }}"
    state: unmounted

- name: "Add {{ target_device }} to {{ directory_to_move }} in fstab"
  mount:
    path: "{{ directory_to_move }}"
    src: "{{ target_device }}"
    fstype: ext4 
    state: present
